//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTE
    {
        public int Id { get; set; }
        public int EmployerNo { get; set; }
        public int EmployerSub { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int NisNumber { get; set; }
        public string Name { get; set; }
        public string Frequence { get; set; }
        public int WeekW { get; set; }
        public Nullable<decimal> Earnings { get; set; }
        public Nullable<decimal> Contribution { get; set; }
        public Nullable<decimal> Penalties { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public string Week1 { get; set; }
        public string Week2 { get; set; }
        public string Week3 { get; set; }
        public string Week4 { get; set; }
        public string Week5 { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
