//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPE
    {
        public int Id { get; set; }
        public int NisNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MaidenName { get; set; }
        public Nullable<System.DateTime> DateOB { get; set; }
        public string Address { get; set; }
        public string Town { get; set; }
        public string Parish { get; set; }
        public string Phone { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
    }
}
