//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPR
    {
        public int Id { get; set; }
        public int EmployerNo { get; set; }
        public int EmployerSub { get; set; }
        public string BusinessName { get; set; }
        public string RealName { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessTown { get; set; }
        public string BusinesssParish { get; set; }
        public string RealAddress { get; set; }
        public string RealTown { get; set; }
        public string RealParish { get; set; }
        public string RealPhone { get; set; }
        public string BusinessPhone { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
    }
}
