//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StandaloneEntities : DbContext
    {
        public StandaloneEntities()
            : base("name=StandaloneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CNTE> CNTE { get; set; }
        public virtual DbSet<EMPE> EMPE { get; set; }
        public virtual DbSet<EMPR> EMPR { get; set; }
    }
}
